### PR TITLE
 Fix eachrow bug #334

### LINKED ISSUE #334: Problem with eachrow and eachrow! + break/continue
Here is a MWE:
```
julia> df = DataFrame(a=1:2, b=2:3);

julia> @eachrow! df begin
               for i in 1:1
                   continue
                   println("and this is super bad as inner loop is affected")
               end
               continue
               println("should not happen")
           end;
and this is super bad as inner loop is affected
should not happen
and this is super bad as inner loop is affected
should not happen
```

### PR DESCRIPTION
**Pull request by pdeffebach**
Fixes #334 

Culprit was code from 0.6 which I believe is not needed.

### CODE REVIEW

File: test/eachrow.jl [hunk 1]
```diff
@@ -195,4 +195,31 @@ end
     @test res.b == [2, 5]
 end
 
+@testset "#334" begin
```
Comment (bkamins) [inline test/eachrow.jl:198]: maybe update the docstring of `@eachrow` and `@eachrow!` with information that what this macro does is that it creates a for loop so, in particular, `break` and `continue` may be used?

**Review by bkamins — APPROVED** [review]
